### ISSUE TITLE
[BUG]: Gazebo localizer crashes due to naming collision

### ISSUE THREAD

**Issue by evan-palmer** [evan-palmer/blue#53]
### Issue Description

The `Localizer` base class implements the method `convert_pose_to_transform`. Within this method, a transform named `tf` is instantiated. This conflicts with the `tf_transformations` import which is assigned the alias `tf`.

### Steps to Reproduce

Launch the system with the Gazebo localizer

### Expected Behavior

The Gazebo localizer shouldn't crash!

### Error Message

```bash
[gazebo_localizer-22] Traceback (most recent call last):
[gazebo_localizer-22]   File "/home/angler/ws_angler/install/blue_localization/lib/blue_localization/gazebo_localizer", line 33, in <module>
[gazebo_localizer-22]     sys.exit(load_entry_point('blue-localization==0.0.1', 'console_scripts', 'gazebo_localizer')())
[gazebo_localizer-22]   File "/home/angler/ws_angler/install/blue_localization/lib/blue_localization/gazebo_localizer", line 25, in importlib_load_entry_point
[gazebo_localizer-22]     return next(matches).load()
[gazebo_localizer-22]   File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
[gazebo_localizer-22]     module = import_module(match.group('module'))
[gazebo_localizer-22]   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
[gazebo_localizer-22]     return _bootstrap._gcd_import(name[level:], package, level)
[gazebo_localizer-22]   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
[gazebo_localizer-22]   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
[gazebo_localizer-22]   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
[gazebo_localizer-22]   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
[gazebo_localizer-22]   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
[gazebo_localizer-22]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
[gazebo_localizer-22]   File "/home/angler/ws_angler/install/blue_localization/lib/python3.10/site-packages/blue_localization/localizer.py", line 28, in <module>
[gazebo_localizer-22]     import tf_transformations as tf
[gazebo_localizer-22]   File "/opt/ros/rolling/lib/python3.10/site-packages/tf_transformations/__init__.py", line 47, in <module>
[gazebo_localizer-22]     import transforms3d
[gazebo_localizer-22]   File "/usr/lib/python3/dist-packages/transforms3d/__init__.py", line 10, in <module>
[gazebo_localizer-22]     from . import quaternions
[gazebo_localizer-22]   File "/usr/lib/python3/dist-packages/transforms3d/quaternions.py", line 26, in <module>
[gazebo_localizer-22]     _MAX_FLOAT = np.maximum_sctype(np.float)
[gazebo_localizer-22]   File "/usr/local/lib/python3.10/dist-packages/numpy/__init__.py", line 313, in __getattr__
[gazebo_localizer-22]     raise AttributeError(__former_attrs__[attr])
[gazebo_localizer-22] AttributeError: module 'numpy' has no attribute 'float'.
[gazebo_localizer-22] `np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
[gazebo_localizer-22] The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
[gazebo_localizer-22]     https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'cfloat'?
```

### Runtime Environment

Dev container on my desktop

**Comment by evan-palmer** [comment]
So I was super wrong about this (it was a bug but not the bug I'm trying to squash). Basically, there is a dependency issue with `tf_transformations`. I'm not quite sure why I opted to use that library in the first place instead of something like scipy. Going to reopen this and remove the dependency in favor of scipy.
